// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy8RwO5dRao9kw_I_WGGDZXxIxI4A-bFQ',
    appId: '1:465601598006:web:3a0fa08c6aa695dfe7fe97',
    messagingSenderId: '465601598006',
    projectId: 'crudproject-49b76',
    authDomain: 'crudproject-49b76.firebaseapp.com',
    storageBucket: 'crudproject-49b76.appspot.com',
    measurementId: 'G-WDQR0T0VSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKnCeh0dolRLNgXkUBPBJlfT-CH272XP8',
    appId: '1:465601598006:android:2e9890b2aa4e5b44e7fe97',
    messagingSenderId: '465601598006',
    projectId: 'crudproject-49b76',
    storageBucket: 'crudproject-49b76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhTYmtmAl4m6OZ2--mOaMiTqPIW0XQIUU',
    appId: '1:465601598006:ios:b133051e1a9acfc5e7fe97',
    messagingSenderId: '465601598006',
    projectId: 'crudproject-49b76',
    storageBucket: 'crudproject-49b76.appspot.com',
    iosBundleId: 'com.example.crudproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhTYmtmAl4m6OZ2--mOaMiTqPIW0XQIUU',
    appId: '1:465601598006:ios:b133051e1a9acfc5e7fe97',
    messagingSenderId: '465601598006',
    projectId: 'crudproject-49b76',
    storageBucket: 'crudproject-49b76.appspot.com',
    iosBundleId: 'com.example.crudproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy8RwO5dRao9kw_I_WGGDZXxIxI4A-bFQ',
    appId: '1:465601598006:web:efb3afeebe8e344fe7fe97',
    messagingSenderId: '465601598006',
    projectId: 'crudproject-49b76',
    authDomain: 'crudproject-49b76.firebaseapp.com',
    storageBucket: 'crudproject-49b76.appspot.com',
    measurementId: 'G-61N46Z06C8',
  );
}
